SELECT a.CAR_ID
     , a.CAR_TYPE
     , CEIL(a.DAILY_FEE * (100 - b.DISCOUNT_RATE) / 100 * 30) AS FEE
FROM CAR_RENTAL_COMPANY_CAR a
INNER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN b ON a.CAR_TYPE = b.CAR_TYPE
AND b.DURATION_TYPE = '30일 이상'
WHERE a.CAR_TYPE IN ('세단', 'SUV')
AND NOT EXISTS (SELECT 1 FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY c
               WHERE a.CAR_ID = c.CAR_ID AND NOT (c.START_DATE > '2022-11-30'
               OR c.END_DATE < '2022-11-01'))
HAVING FEE >= 500000
AND FEE < 2000000
ORDER BY FEE DESC, a.CAR_TYPE, a.CAR_ID;