SELECT MONTH(b.START_DATE) AS MONTH, a.CAR_ID, COUNT(a.CAR_ID) AS RECORDS
FROM (
    SELECT CAR_ID, COUNT(CAR_ID) AS RECORDS
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE (START_DATE BETWEEN '2022-08-01' AND '2022-10-31')
    GROUP BY CAR_ID
    HAVING COUNT(CAR_ID) >= 5
) a
INNER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY b
ON a.CAR_ID = b.CAR_ID
WHERE (START_DATE BETWEEN '2022-08-01' AND '2022-10-31')
GROUP BY MONTH(b.START_DATE), a.CAR_ID
ORDER BY MONTH, a.CAR_ID DESC